
source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'tty'
gem 'pastel'
gem 'tty-prompt', '~> 0.13.1'
gem 'tty-color'
gem 'tty-font'
gem 'tty-spinner'
gem 'launchy'
